"""
Django settings for vendorproject project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dd!ce*)v4+9s4b3@3twx@cf)*n^x8=lmdilxjn!w@8lg#7-z6l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vendorapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vendorproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vendorproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
import json

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Load credentials from key.json
CREDENTIALS_FILE = os.path.join(BASE_DIR, 'credential', 'key.json')

with open(CREDENTIALS_FILE) as f:
    credentials = json.load(f)




# settings.py
CSRF_FAILURE_VIEW = 'vendorapp.views.csrf_failure_view'

# settings.py
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'development')
if ENVIRONMENT == 'production':
    BIND = '127.0.0.1:8000'
    WORKERS = 3
elif ENVIRONMENT == 'development':
    BIND = '127.0.0.1:8000'
    WORKERS = 1


# vendorproject/settings.py
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}



from django.conf import settings

GOOGLE_SERVICE_ACCOUNT_CREDS = {
    "type": "service_account",
    "project_id": "vendors-417407",
    "private_key_id": "539ecce995388eaeab804b40a1b749ff7f4665f0",
    "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDEy1FZLxwAYlHA\nX1+V9iHQvJTjoAvwGHE+081rh+lRqN32KkS07OUDjCZMuxSff6z69xivbtE1JF5l\nzW4+QG9HxMHgza81GUyS+ST37DXDSgPo0PyLwT1IyizkF1IdJ5RihKFkpH7pf4Ia\nIA3EAgUN2QNJtmdRqw1ooUSmJx6RPzq1uOggGQ9zr5Q332tzTvd8l/frtxHAlQLx\n1RLpE2Ru9iy33yJi63OVn03lfKr5Yea1BwpfFQ4rlQZnKXkpz8GuuCe9mATukJfJ\noy9kOOCQ6+rhG6WYilk7NAAqoMGPo/Om7xV3tThYBKjMUbOZ4XBVhDcXoN+fyhQV\n6N35/aRzAgMBAAECggEAInVlf6PHl+ufW/t3Pcd04Vt8CKWIIZjuD22/3PHV8XYL\ns6RwFmwap7XdKPdjI5CUJfepa2KQoGkHXHUNtjnLInp55lattLMC3QNiLUU/nrvx\nlk0tw3zpMbsxBBlvR+qbyWpm5jwFevZYPiHZtzYRU3zp3fjh+4NjnCwM3Lkh2ZW1\noNBXcjdQh3ya2CPxp+1Ug5nBaZolCHAf9bZ1qN71RXE+Bz4K9rlw5YLd+mCce2Xw\n4HBUpwl54/+5EP1nkXLeAjJNLS8DU91MDjI7qBO45Cb6/8jv8eKEwOeKXS7DxGSM\n5J+E69RzfbVa9sDgFcZIoaNRe9GbejTZnIu6VO1jaQKBgQDkU054qGlWEFiEqlw1\nYqYsSL8klg4lSDbvxnIH6gsxFld/gGLjGF6ytEI3AwPJXptDneUDtv7AznL96GAl\nmtzBEPiRY6Uca2dNaV9fJAtnNA/7+unkwfIEIjivAWh//wqrK8O/LGV9d0/sjlE+\nHFfTzZV7D6/er1HQx9K7Nc5mSwKBgQDcpaGy3CKj8WWe6Yc7MuoJNdOPecPE04nS\n7Me5PV7GupNgydw8VFKxcajcL5FpmKtkc3lRFJHqJdPw8aoGw9gIUoR+xY9yLiFL\ndUi8WxhtQ2LDAz3Fuk8Osao7Lqj+IlrQML1BXHJ32T9M0gs8zSi9RTK3dGn5ugqI\nLzzPZXsBeQKBgBtRQEU9WQT8BasxusCEYf9QYNYeweiCAFiltITv4pDn7GYL1Uj4\nZHQbDwUH7k8Ma6UmYf0UytwEl0t7nu1A3wKWZjb25g1FaGGhptB6PocFepgaSBuf\nfLYz5fZCQ990gzFBljTsOeRN/xj9WgkFWRi1Mxo7IT6SWUaSccsGQACLAoGBANGu\ndWPL3v99P90sf966G7508H/Ab1J01N0lNwfKUm74j2XDbw/F8m++W4IjkkSPWRE0\ny21J5wBkwmyOu82B/6KpCFCQ3ijbvbg/1MdqqmPrTceVJPbqfoawP93OEbqwWyzN\npIyglgde5NDUKum07aowQGomry8qpSeV/Gv7PFHBAoGAWOtxJWwtvPKh30pG46cP\niYCoCEovRoqG4Jo8WiKbk1ZIfdS7k47dqTuQh11mxcerTyOMT55tcp+dLxSCEggu\n22vPazlKSI6tlQxM4K3wTbcXrxy4meG+Z01qpklc3MhoH5sQIznj9Tn/bjpFr/n+\n7uliss8HPp0D0pafSiMzfSc=\n-----END PRIVATE KEY-----\n",
    "client_email": "vendor@vendors-417407.iam.gserviceaccount.com",
    "client_id": "104659385798055557977",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/vendor%40vendors-417407.iam.gserviceaccount.com",
    "universe_domain": "googleapis.com"
}
